[sampling]
tick_secs = 30          # Sample health every 30 seconds
max_staleness_secs = 120
grace_period_secs = 45  # Allow up to 45s for head to advance (~7-8 Celestia blocks)

[da_posting]
enabled = false          # Enable when ready to post to Celestia DA
post_every_sample = true  # Post each sample immediately (detailed history for replay)
                         # Batches + ZK proofs are ALSO posted separately (verifiable attestation)

[batching]
window_secs = 600       # Generate batches every 10 minutes (for ZK proofs)
# This is separate from DA posting - batches are for proof generation

[metrics]
head_metric = "das_sampled_chain_head"
headers_metric = "das_total_sampled_headers"
min_increment = 1

[celestia]
rpc_url = "ws://localhost:26658"
grpc_url = "http://localhost:9090"
namespace = "0x2N1CE"
poster_mode = "mock"                # or "real"

# Authentication (Recommended: Use .env file instead of storing here!)
# 
# For security, set credentials via environment variables:
#   1. Copy .env.example to .env
#   2. Set CELESTIA_MNEMONIC or CELESTIA_PRIVATE_KEY in .env
#   3. .env is in .gitignore and won't be committed
#
# Alternatively, uncomment ONE of these (not recommended for production):
# mnemonic = "your twenty four word mnemonic phrase here"
# private_key_hex = "393fdb5def075819de55756b45c9e2c8531a8c78dd6eede483d3440e9457d839"

[proofs]
enabled = false
threshold_percent = 0.95
